general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    # lock_cmd = playerctl --all-players pause && pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # avoid needing to press a key twice.
}

listener {
    timeout = 480                                # 8min
    on-timeout = brightnessctl -s set 10         # dim screen
    on-resume = brightnessctl -r                 # restore brightness
}

# keyboard backlight (optional)
# listener { 
#     timeout = 480
#     on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
#     on-resume = brightnessctl -rd rgb:kbd_backlight
# }

listener {
    timeout = 363                                # 6.3 saar
    on-timeout = pidof hyprlock || hyprlock     # lock screen
}

listener {
    timeout = 660                                # 11min
    on-timeout = hyprctl dispatch dpms off      # turn screen off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 1800                               # 30min
    on-timeout = systemctl suspend              # suspend PC
}
