$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
source = $HOME/.config/hypr/configs/mocha.conf
source = $HOME/.config/hypr/configs/lookandfeel.conf
source = $HOME/.config/hypr/configs/binds.conf
source = $HOME/.config/hypr/configs/animations.conf
source = $HOME/.config/hypr/configs/monitors.conf
source = $HOME/.config/hypr/configs/autostart.conf
source = $HOME/.config/hypr/configs/input.conf
source = $HOME/.config/hypr/configs/envs.conf
